config/routes.rb
Rails.application.routes.draw do

  scope 'admin' do
    resources :bodegas
    resources :zonas
    resources :restaurantes
    resources :excursions
    resources :compras
    resources :sitios
    get 'logs', to: 'admin#logs'
    get 'puestos', to: 'admin#puestos'
    post 'puestos', to: 'admin#puestos'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'asistencia',           to: 'index#asistencia'
  get 'bodegas',              to: 'index#bodegas',          as: :bodegas_show
  get 'checkin',              to: 'index#checkin'
  get 'checkin/:aerolinea',   to: 'index#checkin_detail'
  get 'services',             to: 'index#services'
  get 'restaurantes',         to: 'index#restaurantes',     as: :restaurantes_show
  get 'compras',              to: 'index#compras',          as: :compras_show
  get 'pesa_equipaje',        to: 'index#pesa_equipaje'
  get 'tour_services',        to: 'index#tour_services'
  get 'tour_info',            to: 'index#tour_info'
  get 'excursiones',          to: 'index#excursiones',      as: :excursiones_show
  get 'sitios',               to: 'index#sitios',           as: :sitios_show
  get 'sitio/:uid',           to: 'index#sitio_single',    as: :sitio_single

  get 'admin', to: 'admin#index'

  devise_for :users, controllers: {sessions: "sessions"}

  get ':form/:uid', to: 'index#lugares'

  root to: 'index#index'
end

app/models/restaurante.rb
class Restaurante < ApplicationRecord
  belongs_to :zona
  
  has_attached_file :icono, styles: { original: "500", medium: "300"}
  validates_attachment_content_type :icono, content_type: /\Aimage\/.*\Z/

  has_attached_file :foto, styles: { original: "500", medium: "300"}
  validates_attachment_content_type :foto, content_type: /\Aimage\/.*\Z/
end

app/controllers/restaurantes_controller.rb
class RestaurantesController < ApplicationController
  layout "admin"
  before_action :set_restaurante, only: [:show, :edit, :update, :destroy]

  # GET /restaurantes
  # GET /restaurantes.json
  def index
    @restaurantes = Restaurante.all
    @zonas = Zona.all
    @zona = Zona.new
  end

  # GET /restaurantes/1
  # GET /restaurantes/1.json
  def show
  end

  # GET /restaurantes/new
  def new
    @restaurante = Restaurante.new
  end

  # GET /restaurantes/1/edit
  def edit
  end

  # POST /restaurantes
  # POST /restaurantes.json
  def create
    @restaurante = Restaurante.new(restaurante_params)

    respond_to do |format|
      if @restaurante.save
        format.html { redirect_to @restaurante, notice: 'Restaurante was successfully created.' }
        format.json { render :show, status: :created, location: @restaurante }
      else
        format.html { render :new }
        format.json { render json: @restaurante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurantes/1
  # PATCH/PUT /restaurantes/1.json
  def update
    respond_to do |format|
      if @restaurante.update(restaurante_params)
        format.html { redirect_to @restaurante, notice: 'Restaurante was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurante }
      else
        format.html { render :edit }
        format.json { render json: @restaurante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurantes/1
  # DELETE /restaurantes/1.json
  def destroy
    @restaurante.destroy
    respond_to do |format|
      format.html { redirect_to restaurantes_url, notice: 'Restaurante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurante
      @restaurante = Restaurante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurante_params
      params.require(:restaurante).permit(:direccion, :coordenadas, :nombre, :email, :url, :icono, :foto, :zona_id)
    end
end

app/helpers/restaurantes_helper.rb
module RestaurantesHelper
end

app/views/restaurantes/_form.html.slim
</br>
.col-md-8
  = simple_form_for(@restaurante) do |f|
    = f.error_notification

    .form-inputs
      = f.input :icono, as: :file
      = f.association :zona, label_method: :nombre, value_method: :id, include_blank: false
      = f.input :nombre
      = f.input :direccion
      = f.input :coordenadas
      = f.input :email
      = f.input :url
      = f.input :foto, as: :file

    .form-actions
      = f.button :submit, class: 'button orange'

.clearfix

app/views/restaurantes/edit.html.slim
.container
  h1.orange Editing restaurante

  == render 'form'

app/views/restaurantes/index.html.slim
.container
  h1.orange Zonas
  = simple_form_for @zona, url: zonas_url do |f|
    table.table.table-striped.table-hover
      thead
        tr
          th Nombre
          th Descripcion
          th
      tbody
        - @zonas.each do |zona|
          tr
            td = zona.nombre
            td = zona.descripcion.truncate(120)
            td = link_to content_tag(:i, 'delete_forever' , class: "material-icons"), zona, data: { confirm: 'Are you sure?' }, method: :delete
        tr
            td
              = f.input :nombre
            td
              = f.input :descripcion
            td
              .form-group
                label style="visibility:hidden;" send
                = f.button :submit, "Crear Zona", class: "form-control"

  h1.orange Restaurantes

  table.table.table-striped.table-hover
    thead
      tr
        th Nombre
        th Direccion
        th Zona
        th Coordenadas
        th Email
        th Url
        th
        th
        th

    tbody
      - @restaurantes.each do |restaurante|
        tr
          td = restaurante.nombre
          td = restaurante.direccion
          td = restaurante.zona.nombre
          td = restaurante.coordenadas
          td = restaurante.email
          td = restaurante.url
          td = link_to content_tag(:i, 'more_horiz' , class: "material-icons"), restaurante
          td = link_to content_tag(:i, 'mode_edit' , class: "material-icons"), edit_restaurante_path(restaurante)
          td = link_to content_tag(:i, 'delete_forever' , class: "material-icons"), restaurante, data: { confirm: 'Are you sure?' }, method: :delete

  br

  = link_to 'Nuevo Restaurante', new_restaurante_path, class: 'button orange'

app/views/restaurantes/new.html.slim
.container
  h1.orange Nuevo restaurante

  == render 'form'

app/views/restaurantes/show.html.slim
.container
  p#notice = notice

  h1.orange Restaurante #{@restaurante.nombre}
  br

  table.table.table-striped.table-hover
    tbody
      tr
        td
          strong Nombre:
        td
          = @restaurante.nombre
      tr
        td
          strong Direccion:
        td
          = @restaurante.direccion
      tr
        td
          strong Coordenadas:
        td
          = @restaurante.coordenadas
      tr
        td
          strong Email:
        td
          = @restaurante.email
      tr
        td
          strong Url:
        td
          = @restaurante.url
      tr
        td
          strong Icono:
        td
          = image_tag @restaurante.icono.url, class: 'icon'
      tr
        td
          strong Foto:
        td
          = image_tag @restaurante.foto.url


  = link_to 'Editar', edit_restaurante_path(@restaurante), class: 'button orange float_right'