config/routes.rb
Rails.application.routes.draw do

  scope 'admin' do
    resources :bodegas
    resources :zonas
    resources :restaurantes
    resources :excursions
    resources :compras
    resources :sitios
    get 'logs', to: 'admin#logs'
    get 'puestos', to: 'admin#puestos'
    post 'puestos', to: 'admin#puestos'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'asistencia',           to: 'index#asistencia'
  get 'bodegas',              to: 'index#bodegas',          as: :bodegas_show
  get 'checkin',              to: 'index#checkin'
  get 'checkin/:aerolinea',   to: 'index#checkin_detail'
  get 'services',             to: 'index#services'
  get 'restaurantes',         to: 'index#restaurantes',     as: :restaurantes_show
  get 'compras',              to: 'index#compras',          as: :compras_show
  get 'pesa_equipaje',        to: 'index#pesa_equipaje'
  get 'tour_services',        to: 'index#tour_services'
  get 'tour_info',            to: 'index#tour_info'
  get 'excursiones',          to: 'index#excursiones',      as: :excursiones_show
  get 'sitios',               to: 'index#sitios',           as: :sitios_show
  get 'sitio/:uid',           to: 'index#sitio_single',    as: :sitio_single

  get 'admin', to: 'admin#index'

  devise_for :users, controllers: {sessions: "sessions"}

  get ':form/:uid', to: 'index#lugares'

  root to: 'index#index'
end

app/models/sitio.rb
class Sitio < ApplicationRecord
  belongs_to :zona

  before_save { |t| t.uid = t.nombre.downcase.dasherize.tr(' ','-') }

  has_attached_file :foto, styles: { original: "500", medium: "300"}
  validates_attachment_content_type :foto, content_type: /\Aimage\/.*\Z/
end

app/controllers/sitios_controller.rb
class SitiosController < ApplicationController
  layout "admin"
  before_action :set_sitio, only: [:show, :edit, :update, :destroy]

  # GET /sitios
  # GET /sitios.json
  def index
    @sitios = Sitio.all
    @zonas = Zona.all
    @zona = Zona.new
  end

  # GET /sitios/1
  # GET /sitios/1.json
  def show
  end

  # GET /sitios/new
  def new
    @sitio = Sitio.new
  end

  # GET /sitios/1/edit
  def edit
  end

  # POST /sitios
  # POST /sitios.json
  def create
    @sitio = Sitio.new(sitio_params)

    respond_to do |format|
      if @sitio.save
        format.html { redirect_to @sitio, notice: 'Sitio was successfully created.' }
        format.json { render :show, status: :created, location: @sitio }
      else
        format.html { render :new }
        format.json { render json: @sitio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sitios/1
  # PATCH/PUT /sitios/1.json
  def update
    respond_to do |format|
      if @sitio.update(sitio_params)
        format.html { redirect_to @sitio, notice: 'Sitio was successfully updated.' }
        format.json { render :show, status: :ok, location: @sitio }
      else
        format.html { render :edit }
        format.json { render json: @sitio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sitios/1
  # DELETE /sitios/1.json
  def destroy
    @sitio.destroy
    respond_to do |format|
      format.html { redirect_to sitios_url, notice: 'Sitio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sitio
      @sitio = Sitio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sitio_params
      params.require(:sitio).permit(:nombre, :detalle, :foto, :zona_id)
    end
end

app/helpers/sitios_helper.rb
module SitiosHelper
end

app/views/sitios/_form.html.slim
</br>
.col-md-8
  = simple_form_for(@sitio) do |f|
    = f.error_notification

    .form-inputs
      = f.input :foto, as: :file
      = f.association :zona, label_method: :nombre, value_method: :id, include_blank: false
      = f.input :nombre
      = f.input :detalle

    .form-actions
      = f.button :submit, class: 'button orange'

.clearfix

app/views/sitios/edit.html.slim
.container
  h1.orange Actualizar Sitio Historico

  == render 'form'

app/views/sitios/index.html.slim
.container
  h1.orange Zonas
  = simple_form_for @zona, url: zonas_url do |f|
    table.table.table-striped.table-hover
      thead
        tr
          th Nombre
          th Descripcion
          th
      tbody
        - @zonas.each do |zona|
          tr
            td = zona.nombre
            td = zona.descripcion.truncate(120)
            td = link_to content_tag(:i, 'delete_forever' , class: "material-icons"), zona, data: { confirm: 'Are you sure?' }, method: :delete
        tr
            td
              = f.input :nombre
            td
              = f.input :descripcion
            td
              .form-group
                label style="visibility:hidden;" send
                = f.button :submit, "Crear Zona", class: "form-control"

  h1.orange Lista de Sitios Turísticos

  table.table.table-striped.table-hover
    thead
      tr
        th Nombre
        th uid
        th Detalle
        th Zona
        th
        th
        th

    tbody
      - @sitios.each do |sitio|
        tr
          td = sitio.nombre
          td = sitio.uid
          td = sitio.detalle
          td = sitio.zona.nombre
          td = link_to content_tag(:i, 'more_horiz' , class: "material-icons"), sitio
          td = link_to content_tag(:i, 'mode_edit' , class: "material-icons"), edit_sitio_path(sitio)
          td = link_to content_tag(:i, 'delete_forever' , class: "material-icons"), sitio, data: { confirm: 'Are you sure?' }, method: :delete

  br

  = link_to 'Nuevo Sitio Turistico', new_sitio_path, class: 'button orange'

app/views/sitios/new.html.slim
.container
  h1.orange Nuevo Sitio Historico

  == render 'form'

app/views/sitios/show.html.slim
.container
  p#notice = notice

  h1.orange Sitio Historico #{@sitio.nombre}
  br

  table.table.table-striped.table-hover
    tbody
      tr
        td
          strong Nombre:
        td
          = @sitio.nombre
      tr
        td
          strong uid:
        td
          = @sitio.uid
      tr
        td
          strong Zona:
        td
          = @sitio.zona.nombre
      tr
        td
          strong Detalle:
        td
          = @sitio.detalle
      tr
        td
          strong Foto:
        td
          = image_tag @sitio.foto.url

  = link_to 'Editar', edit_sitio_path(@sitio), class: 'button orange float_right'