config/routes.rb
Rails.application.routes.draw do

  scope 'admin' do
    resources :bodegas
    resources :zonas
    resources :restaurantes
    resources :excursions
    resources :compras
    resources :sitios
    get 'logs', to: 'admin#logs'
    get 'puestos', to: 'admin#puestos'
    post 'puestos', to: 'admin#puestos'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'asistencia',           to: 'index#asistencia'
  get 'bodegas',              to: 'index#bodegas',          as: :bodegas_show
  get 'checkin',              to: 'index#checkin'
  get 'checkin/:aerolinea',   to: 'index#checkin_detail'
  get 'services',             to: 'index#services'
  get 'restaurantes',         to: 'index#restaurantes',     as: :restaurantes_show
  get 'compras',              to: 'index#compras',          as: :compras_show
  get 'pesa_equipaje',        to: 'index#pesa_equipaje'
  get 'tour_services',        to: 'index#tour_services'
  get 'tour_info',            to: 'index#tour_info'
  get 'excursiones',          to: 'index#excursiones',      as: :excursiones_show
  get 'sitios',               to: 'index#sitios',           as: :sitios_show
  get 'sitio/:uid',           to: 'index#sitio_single',    as: :sitio_single

  get 'admin', to: 'admin#index'

  devise_for :users, controllers: {sessions: "sessions"}

  get ':form/:uid', to: 'index#lugares'

  root to: 'index#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bodega.rb
class Bodega < ApplicationRecord
  belongs_to :zona

  has_attached_file :icono, styles: { original: "500", medium: "300"}
  validates_attachment_content_type :icono, content_type: /\Aimage\/.*\Z/

  has_attached_file :foto, styles: { original: "500", medium: "300"}
  validates_attachment_content_type :foto, content_type: /\Aimage\/.*\Z/
end

app/models/compra.rb
class Compra < ApplicationRecord
  belongs_to :zona

  has_attached_file :icono, styles: { original: "500", medium: "300"}
  validates_attachment_content_type :icono, content_type: /\Aimage\/.*\Z/
end

app/models/excursion.rb
class Excursion < ApplicationRecord
  belongs_to :zona

  has_attached_file :icono, styles: { original: "500", medium: "300"}
  validates_attachment_content_type :icono, content_type: /\Aimage\/.*\Z/

end

app/models/login.rb
class Login < ApplicationRecord
end

app/models/restaurante.rb
class Restaurante < ApplicationRecord
  belongs_to :zona
  
  has_attached_file :icono, styles: { original: "500", medium: "300"}
  validates_attachment_content_type :icono, content_type: /\Aimage\/.*\Z/

  has_attached_file :foto, styles: { original: "500", medium: "300"}
  validates_attachment_content_type :foto, content_type: /\Aimage\/.*\Z/
end

app/models/sitio.rb
class Sitio < ApplicationRecord
  belongs_to :zona

  before_save { |t| t.uid = t.nombre.downcase.dasherize.tr(' ','-') }

  has_attached_file :foto, styles: { original: "500", medium: "300"}
  validates_attachment_content_type :foto, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable
end

app/models/zona.rb
class Zona < ApplicationRecord
  has_many :bodegas
  has_many :excursions
  has_many :compras
  has_many :sitios
  has_many :restaurantes
  before_save { |t| t.uid = t.nombre.downcase.dasherize.tr(' ','-') }
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout "admin"
  skip_before_action :restrict_access, only: [:index]
  before_action :authenticate_user!

  def index
    if current_user.email == 'admin@easy-travel.com.ar'
      Login.create(ip: request.remote_ip, ua: request.user_agent)
    end
  end

  def logs
    @logs = Login.select("created_at, ip, ua")
    render json: @logs.to_json
  end

  def puestos
    if params[:act] == "up"
      cookies[:puesto] = { value: "true", expires: 1.year.from_now }
      cookies[:ip] = { value: params[:ip], expires: 1.year.from_now }
      flash[:notice] = "Puesto registrado exitosamente"
    elsif params[:act] == "down"
      cookies.delete :puesto
      cookies.delete :ip
      flash[:notice] = "Puesto eliminado exitosamente"
    end

  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bodegas_helper.rb
module BodegasHelper
end

app/helpers/compras_helper.rb
module ComprasHelper
end

app/helpers/excursions_helper.rb
module ExcursionsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/restaurantes_helper.rb
module RestaurantesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sitios_helper.rb
module SitiosHelper
end

app/helpers/zonas_helper.rb
module ZonasHelper
end

app/views/admin/index.html.slim
#mainContainer
  img#logo.large src="/images/logo_time.png" alt=""
  h1.orange Bienvenido, seleccione una opcion para continuar.
  br
  = link_to('Logout', destroy_user_session_path, method: :delete, class: "button orange")

app/views/admin/puestos.html.slim
#mainContainer
  img#logo.large src="/images/logo_time.png" alt=""
  br
  - if cookies[:puesto] == "true"
    h2.orange Este puesto ya esta registrado. 
    br
    a.button.orange href="#{puestos_url}/?act=down" Eliminar
  - else
    h2.orange Desea registrar el puesto?
    br
    = form_tag controller: "admin", action:"puestos", method:"POST" do
      = text_field_tag(:ip, nil, placeholder:"IP Privada", required:"true")
      = hidden_field_tag(:act, "up") 
      = submit_tag("Registrar", class:"button orange")

app/views/index/bodegas.html.slim
#mainContainer
  img#logo.small src="/images/logo_time.png" alt=""
  a href=tour_info_url
    img#miniServicios src="/images/icono_informacion.png" alt=""

  #mainFrame
    div
      a href=restaurantes_show_url
        img.wineArrow.left src="/images/triangulo_vino.png" alt=""

      img#mainIcon src="/images/icono_central_bodegas.png" alt=""

      a href=compras_show_url
        img.wineArrow.right src="/images/triangulo_vino.png" alt=""

      p.mainText.wine Bodegas
      p.mediumText.wine ¿Qué zona te gustaría visitar?

      - unless @zonas.blank?
        .dropdown.wine
          #dropdownMenu1.button.btn.btn-default.dropdown-toggle type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"
            | Seleccione una opción
            /i.material-icons arrow_drop_down
          ul.dropdown-menu aria-labelledby="dropdownMenu1"
            - @zonas.each do |zona|
              li
                a href="#{bodegas_show_url}/#{zona.uid}" = zona.nombre.upcase

  a href=tour_info_url
    p#footerNavigation.wine
      img.wineArrow.left src="/images/triangulo_vino.png" alt=""  Volver Atrás

app/views/index/checkin.html.slim
#mainContainer
  img#logo.small src="/images/logo_time.png" alt=""
  a href== tour_services_url
    img#miniServicios src="/images/icono_servicios.png" alt=""
  #mainFrame
    div
      a href=""
        img.blueArrow src="/images/triangulo_azul.png" alt=""
      img#mainIcon src="/images/checkin_anterior.png" alt=""
      a href=pesa_equipaje_url
        img.blueArrow.right src="/images/triangulo_azul.png" alt=""
      p.mainText.blue Check In
    div
      p.mediumText.blue Selecciona tu aerolínea
      a href="#{checkin_url}/latam"
        img.icon-circle src="/images/latam.png"
      a href="#{checkin_url}/aerolineas_argentinas"
        img.icon-circle src="/images/aeroar.png"
      

  a href=tour_services_url
    p#footerNavigation.blue
      img.blueArrow src="/images/triangulo_azul.png" alt=""
      | Volver Atrás

app/views/index/checkin_detail.html.slim
#mainContainer
  a href== tour_services_url
    img#miniServicios src="/images/icono_servicios.png" alt=""
  br
  iframe src==@url

  a href=tour_services_url
    p#footerNavigation.blue
      img.blueArrow src="/images/triangulo_azul.png" alt=""
      | Volver Atrás

app/views/index/compras.html.slim
#mainContainer

  img#logo.small src="/images/logo_time.png" alt=""

  a href=tour_info_url
    img#miniServicios src="/images/icono_informacion.png" alt=""

  #mainFrame
    div
      a href=bodegas_show_url
        img.wineArrow.left src="/images/triangulo_vino.png" alt=""
      img#mainIcon src="/images/icono_compras.png" alt=""
      a href=sitios_show_url
        img.wineArrow.right src="/images/triangulo_vino.png" alt=""
      p.mainText.orange Compras
      p.mediumText ¿Qué zona te gustaría visitar?

      - unless @zonas.blank?
        .dropdown.wine
          #dropdownMenu1.button.btn.btn-default.dropdown-toggle type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"
            | Seleccione una opción
            /i.material-icons arrow_drop_down
          ul.dropdown-menu aria-labelledby="dropdownMenu1"
            - @zonas.each do |zona|
              li
                a href="#{compras_show_url}/#{zona.uid}" = zona.nombre.upcase

  a href=tour_info_url
    p#footerNavigation.wine
      img.wineArrow.left src="/images/triangulo_vino.png" alt=""
      | Volver Atrás

app/views/index/excursiones.html.slim
#mainContainer
  img#logo.small src="/images/logo_time.png" alt=""
  a href=tour_info_url
    img#miniServicios.left src="/images/icono_informacion.png" alt=""
  #mainFrame
    div
      a href=sitios_show_url
        img.wineArrow.left src="/images/triangulo_vino.png" alt=""
      img#mainIcon.restaurantesIcon src="/images/icono_excursiones.png" alt=""
      a href=restaurantes_show_url
        img.wineArrow.right src="/images/triangulo_vino.png" alt=""
      p.mainText.wine Excursiones
      - unless @zonas.blank?
        .dropdown
          #dropdownMenu1.button.btn.btn-default.dropdown-toggle type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"
            | Seleccione una opción
            /i.material-icons arrow_drop_down
          ul.dropdown-menu aria-labelledby="dropdownMenu1"
            - @zonas.each do |zona|
              li
                a href="#{excursiones_show_url}/#{zona.uid}" = zona.nombre.upcase
  a href=tour_info_url
    p#footerNavigation.gold
      img.wineArrow.left src="/images/triangulo_dorado.png" alt=""
      | Volver Atrás

app/views/index/index.html.slim
#mainContainer
  img#logo.large src="/images/logo_time.png" alt=""
  #languageBar
    p 
      <a href="">Español</a> | <a href="">Inglés</a> | <a href="">Portugués</a>
  h3.orange ¿Donde te encontrás?
  #placeSelectorContainer
    p
      span País
      select dir="rtl"
        option value="" Argentina
    p
      span Provincia
      select.onChangeRedirect dir="rtl"
        option value=services_url Mendoza

app/views/index/lugares.html.slim
#mainContainer
  img#logo.small src="/images/logo_time.png" alt=""
  a href=tour_info_url
    img#miniServicios src="/images/icono_informacion.png" alt=""
  div
    div
      p.mainText.orange = @zona.nombre
      p.mainDesc.wine = @zona.descripcion

    div#lugaresContainer
      img.wineArrow.left.lugarBefore src="/images/triangulo_vino.png" alt=""
      - unless @lugares.nil?
        - sizes = { 0 => "col-md-4", 1 => "col-md-3", 2 => "col-md-4", 3 => "col-md-3", 4 => "col-md-4 col-md-offset-2", 5 => "col-md-4"}
        - @lugares.each.with_index(1) do |lugar, i|
          - if i == 1 || i % 4 == 0 || i % 6 == 0
            <div class="row">

          div id="#{i}" class="#{sizes[i % 6]}"
            .lugarContainers
              a class="lugarIcon #{"onClickShow" unless lugar.is_a?(Sitio)}" href="#{lugar.is_a?(Sitio) ? sitio_single_url(lugar.uid) : "#" }"
                img src="#{lugar.is_a?(Sitio) ? lugar.foto.url : lugar.icono.url }" alt=""
              br
              - unless lugar.is_a?(Sitio)
                - unless lugar.is_a?(Excursion) || lugar.is_a?(Compra)
                  img.lugarFoto src="#{lugar.foto.url}" alt=""
                p.lugarDesc
                  | #{lugar.direccion}
                  br
                  | e-mail: #{lugar.email}
                  - if lugar.is_a?(Bodega)
                    br
                    | Reservas: #{lugar.reservas}
                a.lugarUrl href="#"
                  p.orange.basic Dirigirse al sitio oficial
                div#modalframe.onloadhide
                  object#frame type="text/html" data="#{lugar.url}" width="1500" height="800"
              - else
                h4.orange = lugar.nombre.upcase
          - if i % 3 == 0 && i % 5 > 2 || i % 5 == 0
            </div>
        - if @lugares.length % 3 != 0 && @lugares.length % 5 != 0 && @lugares.length % 5 < 2
          </div>

  .clearfix
  a href=tour_info_url
    p#footerNavigation.lugares.orange
      img.wineArrow src="/images/triangulo_naranja.png" alt=""
      | Volver Atrás

app/views/index/pesa_equipaje.html.slim
#mainContainer
  img#logo.small src="/images/logo_time.png" alt=""
  a href=tour_services_url
    img#miniServicios src="/images/icono_servicios.png" alt=""
  #mainFrame
    div
      a href=checkin_url
        img.blueArrow src="/images/triangulo_azul.png" alt=""
      img#mainIcon src="/images/valija_central.png" alt="" 
      a href=asistencia_url
        img.blueArrow.right src="/images/triangulo_azul.png" alt=""
      p.mainText.blue Pesá tu <br>equipaje
      p#output.mainText.blue.peso Leyendo ... 
      #pasosContainer
        img.pasosPesa.pasosPesa1.onloadhide src="/images/paso_1.png" alt=""
        img.pasosPesa.pasosPesa2.onloadhide src="/images/paso_2.png" alt=""
        img.pasosPesa.pasosPesa3.onloadhide src="/images/paso_3.png" alt=""
  a href=tour_services_url
    p#footerNavigation.blue
      img.blueArrow src="/images/triangulo_azul.png" alt=""
      | Volver Atrás

  - unless @wss.blank?
    input type="hidden" value="#{cookies[:ip]}" id="ip"
    javascript:
      var wsUri = "ws://" + $('#ip').val() + ":11000" ;
      var $output = $('#output');
      
      function init() {
        connectWebSocket();
      }

      function connectWebSocket() {
        websocket = new WebSocket(wsUri);

        websocket.onopen = function(evt) {
          console.log('Connected');
        };
        websocket.onclose = function(evt) {
          console.log('Disconnected');
        };
        websocket.onmessage = function(evt) {
          writeToScreen(evt.data);
        };
        websocket.onerror = function(evt) {
          console.error(evt)
        };
      }

      function writeToScreen(message) {
        $output.html(message);
      }

      //FIXME: Turbolinks
      window.addEventListener("load", init, false);

app/views/index/restaurantes.html.slim
#mainContainer
  img#logo.small src="/images/logo_time.png" alt=""
  a href=tour_info_url
    img#miniServicios.left src="/images/icono_informacion.png" alt=""
  #mainFrame
    div
      a href=excursiones_show_url
        img.wineArrow.left src="/images/triangulo_dorado.png" alt=""
      img#mainIcon.restaurantesIcon src="/images/icono_restaurantes.png" alt=""
      a href=bodegas_show_url
        img.wineArrow.right src="/images/triangulo_dorado.png" alt=""
      p.mainText.gold Bares & <br> Restaurantes
      - unless @zonas.blank?
        .dropdown
          #dropdownMenu1.button.btn.btn-default.dropdown-toggle type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"
            | Seleccione una opción
            /i.material-icons arrow_drop_down
          ul.dropdown-menu aria-labelledby="dropdownMenu1"
            - @zonas.each do |zona|
              li
                a href="#{restaurantes_show_url}/#{zona.uid}" = zona.nombre.upcase
  a href=tour_info_url
    p#footerNavigation.gold
      img.wineArrow.left src="/images/triangulo_dorado.png" alt=""
      | Volver Atrás

app/views/index/services.html.slim
#mainContainer
  img#logo.medium src="/images/logo_time.png" alt=""
  #servicesContainer
    a href=tour_services_url
      #servicesIconContainer
        img#serviceIcon src="/images/icono_servicios.png" alt=""
        p.mainText.blue Servicios <br> Turísticos

    a href=tour_info_url
      #servicesIconContainer
        img#serviceIcon src="/images/icono_informacion.png" alt=""
        p.mainText.orange Información <br> Turística
  
  a href=root_url
    p#footerNavigation.blue
      img.blueArrow src="/images/triangulo_azul.png" alt=""
      | Volver Atrás

app/views/index/sitio_single.html.slim
#mainContainer
  img#logo.small src="/images/logo_time.png" alt=""
  a href=tour_info_url
    img#miniServicios.left src="/images/icono_informacion.png" alt=""
  div
    div
      p.mainText.gold = @sitio.nombre.upcase
      p.mainDesc.noborder = @sitio.detalle
    br
  #mainFrame
    img src=@sitio.foto.url

  a href=tour_info_url
    p#footerNavigation.lugares.orange
      img.wineArrow src="/images/triangulo_naranja.png" alt=""
      | Volver Atrás

app/views/index/sitios.html.slim
#mainContainer
  img#logo.small src="/images/logo_time.png" alt=""
  a href=tour_info_url
    img#miniServicios.left src="/images/icono_informacion.png" alt=""
  #mainFrame
    div
      a href=compras_show_url
        img.wineArrow.left src="/images/triangulo_dorado.png" alt=""
      img#mainIcon.restaurantesIcon src="/images/icono_sitios.png" alt=""
      a href=excursiones_show_url
        img.wineArrow.right src="/images/triangulo_dorado.png" alt=""
      p.mainText.gold Sitios <br> Historicos
      - unless @zonas.blank?
        .dropdown
          #dropdownMenu1.button.btn.btn-default.dropdown-toggle type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"
            | Seleccione una opción
            /i.material-icons arrow_drop_down
          ul.dropdown-menu aria-labelledby="dropdownMenu1"
            - @zonas.each do |zona|
              li
                a href="#{sitios_show_url}/#{zona.uid}" = zona.nombre.upcase
  a href=tour_info_url
    p#footerNavigation.gold
      img.wineArrow.left src="/images/triangulo_dorado.png" alt=""
      | Volver Atrás

app/views/index/tour_info.html.slim
#mainContainer
  #logo.small src="/images/logo_time.png" alt=""
  #circlesContainer
    img#optionsBackground src="/images/icono_central_info.png" alt=""

    a.optionIconContainer.pesa href="#"
      img.optionIcon src="/images/circulo_turismo.png" alt=""
    a.optionIconContainer.asistencia href=excursiones_show_url
      img.optionIcon src="/images/circulo_excursiones.png" alt=""
    a.optionIconContainer.alquiler href=sitios_show_url
      img.optionIcon src="/images/circulo_sitios.png" alt=""
    a.optionIconContainer.paquetes href=compras_show_url
      img.optionIcon src="/images/circulo_compras.png" alt=""
    a.optionIconContainer.venta href=bodegas_show_url
      img.optionIcon src="/images/circulo_bodegas.png" alt=""
    a.optionIconContainer.checkin href=restaurantes_show_url
      img.optionIcon src="/images/circulo_restaurantes.png" alt=""

  a href=services_url
    p#footerNavigation.orange
      img.blueArrow src="/images/triangulo_naranja.png" alt=""
      | Volver Atrás

app/views/index/tour_services.html.slim
#mainContainer
  img#logo.small src="/images/logo_time.png" alt="" 
  #circlesContainer
    img#optionsBackground src="/images/icono_central_servicios.png" alt=""        
    a.optionIconContainer.pesa href=pesa_equipaje_url
      img.optionIcon src="/images/circulo_pesa.png" alt="" 
    a.optionIconContainer.asistencia href=asistencia_url
      img.optionIcon src="/images/circulo_asistencia.png" alt="" 
    a.optionIconContainer.alquiler href="#" 
      img.optionIcon src="/images/circulo_alquiler.png" alt="" 
    a.optionIconContainer.paquetes href="#"
      img.optionIcon src="/images/circulo_paquetes.png" alt="" 
    a.optionIconContainer.venta href="#"
      img.optionIcon src="/images/circulo_venta.png" alt=""
    a.optionIconContainer.checkin href=checkin_url
      img.optionIcon src="/images/circulo_check.png" alt="" 
          
  a href=services_url
    p#footerNavigation.blue
      img.blueArrow src="/images/triangulo_azul.png" alt=""
      | Volver Atrás

app/views/layouts/_messages.html.slim
- flash.each do |key, value| 
  div class="alert alert-dismissible alert-#{key == 'alert' ? "danger" : key == 'notice' ? "info" : key}" role="alert"
    button.close type="button" data-dismiss="alert" aria-label="Close" 
      span aria-hidden="true" &times;
    = value
        

app/views/layouts/_sidebar.html.slim
.w3-sidebar.w3-bar-block style="width:15%;"
  img#logo.small src="/images/logo_time.png" alt=""
  hr
  h3.w3-bar-item.orange Administrador
  hr
  a.w3-bar-item.w3-button href=bodegas_url Bodegas
  a.w3-bar-item.w3-button href=restaurantes_url Restaurantes
  a.w3-bar-item.w3-button href=excursions_url Excursiones
  a.w3-bar-item.w3-button href=compras_url Compras
  a.w3-bar-item.w3-button href=sitios_url Sitios Historicos
  a.w3-bar-item.w3-button href=puestos_url Puestos
  hr
  = link_to('Logout', destroy_user_session_path, method: :delete, class: " w3-bar-item w3-button")

app/views/layouts/admin.html.slim
doctype html
html
  head
    
    title EasyTravel
    = csrf_meta_tags
    
    meta http-equiv="Content-Type" content="text/html; charset=utf-8"
    link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"
    link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"
    
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    
    script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"
    link href='http://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext' rel='stylesheet' type='text/css'
    link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"
  body
    
    #wholeContainer
      - if user_signed_in?
        = render  'layouts/sidebar'

      div style="margin-left:15%; position: relative;"
        = render 'layouts/messages'
        = yield 
      
      

    javascript:
      function w3_open() {
        document.getElementById("main").style.marginLeft = "25%";
        document.getElementById("mySidebar").style.width = "25%";
        document.getElementById("mySidebar").style.display = "block";
        document.getElementById("openNav").style.display = 'none';
      }
      function w3_close() {
        document.getElementById("main").style.marginLeft = "0%";
        document.getElementById("mySidebar").style.display = "none";
        document.getElementById("openNav").style.display = "inline-block";
      } 
    
    

app/views/layouts/application.html.slim
doctype html
html
  head
    
    title EasyTravel
    = csrf_meta_tags
    
    meta http-equiv="Content-Type" content="text/html; charset=utf-8"
    link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"
    link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"
    link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"
    link rel="manifest" href="/manifest.json"
    link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5"
    meta name="theme-color" content="#ffffff"
    
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    link href='http://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext' rel='stylesheet' type='text/css'
    script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"    
    link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"
  
  body
    div#wholeContainer
      = yield