config/routes.rb
Rails.application.routes.draw do

  scope 'admin' do
    resources :bodegas
    resources :zonas
    resources :restaurantes
    resources :excursions
    resources :compras
    resources :sitios
    get 'logs', to: 'admin#logs'
    get 'puestos', to: 'admin#puestos'
    post 'puestos', to: 'admin#puestos'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'asistencia',           to: 'index#asistencia'
  get 'bodegas',              to: 'index#bodegas',          as: :bodegas_show
  get 'checkin',              to: 'index#checkin'
  get 'checkin/:aerolinea',   to: 'index#checkin_detail'
  get 'services',             to: 'index#services'
  get 'restaurantes',         to: 'index#restaurantes',     as: :restaurantes_show
  get 'compras',              to: 'index#compras',          as: :compras_show
  get 'pesa_equipaje',        to: 'index#pesa_equipaje'
  get 'tour_services',        to: 'index#tour_services'
  get 'tour_info',            to: 'index#tour_info'
  get 'excursiones',          to: 'index#excursiones',      as: :excursiones_show
  get 'sitios',               to: 'index#sitios',           as: :sitios_show
  get 'sitio/:uid',           to: 'index#sitio_single',    as: :sitio_single

  get 'admin', to: 'admin#index'

  devise_for :users, controllers: {sessions: "sessions"}

  get ':form/:uid', to: 'index#lugares'

  root to: 'index#index'
end

app/models/excursion.rb
class Excursion < ApplicationRecord
  belongs_to :zona

  has_attached_file :icono, styles: { original: "500", medium: "300"}
  validates_attachment_content_type :icono, content_type: /\Aimage\/.*\Z/

end

app/controllers/excursions_controller.rb
class ExcursionsController < ApplicationController
  layout "admin"
  before_action :set_excursion, only: [:show, :edit, :update, :destroy]

  # GET /excursions
  # GET /excursions.json
  def index
    @excursions = Excursion.all
    @zonas = Zona.all
    @zona = Zona.new
  end

  # GET /excursions/1
  # GET /excursions/1.json
  def show
  end

  # GET /excursions/new
  def new
    @excursion = Excursion.new
  end

  # GET /excursions/1/edit
  def edit
  end

  # POST /excursions
  # POST /excursions.json
  def create
    @excursion = Excursion.new(excursion_params)

    respond_to do |format|
      if @excursion.save
        format.html { redirect_to @excursion, notice: 'Excursion was successfully created.' }
        format.json { render :show, status: :created, location: @excursion }
      else
        format.html { render :new }
        format.json { render json: @excursion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /excursions/1
  # PATCH/PUT /excursions/1.json
  def update
    respond_to do |format|
      if @excursion.update(excursion_params)
        format.html { redirect_to @excursion, notice: 'Excursion was successfully updated.' }
        format.json { render :show, status: :ok, location: @excursion }
      else
        format.html { render :edit }
        format.json { render json: @excursion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /excursions/1
  # DELETE /excursions/1.json
  def destroy
    @excursion.destroy
    respond_to do |format|
      format.html { redirect_to excursions_url, notice: 'Excursion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_excursion
      @excursion = Excursion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def excursion_params
      params.require(:excursion).permit(:direccion, :email, :reservas, :telefono, :url, :icono, :zona_id)
    end
end

app/helpers/excursions_helper.rb
module ExcursionsHelper
end

app/views/excursions/_form.html.slim
</br>
.col-md-8
  = simple_form_for(@excursion) do |f|
    = f.error_notification

    .form-inputs
      = f.input :icono, as: :file 
      = f.association :zona, label_method: :nombre, value_method: :id, include_blank: false
      = f.input :direccion
      = f.input :email
      = f.input :reservas
      = f.input :telefono
      = f.input :url

    .form-actions
      = f.button :submit, class: 'button orange'

.clearfix

app/views/excursions/edit.html.slim
.container
  h1.orange Actualizar excursion

  == render 'form'

app/views/excursions/index.html.slim
.container
  h1.orange Zonas
  = simple_form_for @zona, url: zonas_url do |f|
    table.table.table-striped.table-hover
      thead
        tr
          th Nombre
          th Descripcion
          th
      tbody
        - @zonas.each do |zona|
          tr
            td = zona.nombre
            td = zona.descripcion.truncate(120)
            td = link_to content_tag(:i, 'delete_forever' , class: "material-icons"), zona, data: { confirm: 'Are you sure?' }, method: :delete
        tr
            td
              = f.input :nombre
            td
              = f.input :descripcion
            td
              .form-group
                label style="visibility:hidden;" send
                = f.button :submit, "Crear Zona", class: "form-control" 
                
  h1.orange Lista de Excursiones

  table.table.table-striped.table-hover
    thead
      tr
        th Direccion
        th Email
        th Reservas
        th Telefono
        th Url
        th Zona
        th
        th
        th

    tbody
      - @excursions.each do |excursion|
        tr
          td = excursion.direccion
          td = excursion.email
          td = excursion.reservas
          td = excursion.telefono
          td = excursion.url
          td = excursion.zona.nombre
          td = link_to content_tag(:i, 'more_horiz' , class: "material-icons"), excursion
          td = link_to content_tag(:i, 'mode_edit' , class: "material-icons"), edit_excursion_path(excursion)
          td = link_to content_tag(:i, 'delete_forever' , class: "material-icons"), excursion, data: { confirm: 'Are you sure?' }, method: :delete

  br

  = link_to 'Nueva Excursion', new_excursion_path, class: 'button orange'

app/views/excursions/new.html.slim
.container
  h1.orange Nueva excursion

  == render 'form'

app/views/excursions/show.html.slim
.container
  p#notice = notice

  h1.orange Excursion
  br

  table.table.table-striped.table-hover
    tbody
      tr
        td
          strong Zona:
        td
          = @excursion.zona.nombre
      tr
        td
          strong Direccion:
        td
          = @excursion.direccion
      tr
        td
          strong Email:
        td
          = @excursion.email
      tr
        td
          strong Reservas:
        td
          = @excursion.reservas
      tr
        td
          strong Telefono:
        td
          = @excursion.telefono
      tr
        td
          strong Url:
        td
          = @excursion.url
      tr
        td
          strong Icono:
        td
          = image_tag @excursion.icono.url, class: 'icon'

  = link_to 'Editar', edit_excursion_path(@excursion), class: 'button orange float_right'